REM Delete Garbage Files
del *.aps
del *.ilk
del *.map
del *.ncb
del *.opt
del *.plg
del *.pbi
del *.pbo
del *.pbt
del *.pdb
del *.tmp
del *.bak
del *.log
del *.user
del *.cfg
del Draw.lib
del Extensions.lib
del Fonts.lib
del Fps.lib
del Lighting.lib
del Logger.lib
del MatrixOperations.lib
del MultiLanguage.lib
del Sound.lib
del SpeedControl.lib
del Network.lib
del OpenGLFramework.lib